
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package org.example.parser;

/** CUP generated interface containing symbol constants. */
public interface Symbols {
  /* terminals */
  public static final int DIVIDE = 20;
  public static final int FUNCTION = 9;
  public static final int GE = 24;
  public static final int UMINUS = 38;
  public static final int LPAREN = 28;
  public static final int INT = 33;
  public static final int MINUS = 18;
  public static final int RPAREN = 29;
  public static final int DEFINE = 2;
  public static final int NOT = 16;
  public static final int SEMICOLON = 30;
  public static final int AND = 14;
  public static final int ELSEIF = 6;
  public static final int LT = 21;
  public static final int OR = 15;
  public static final int COMMA = 31;
  public static final int LOOP = 8;
  public static final int PLUS = 17;
  public static final int ASSIGN = 27;
  public static final int IF = 4;
  public static final int ID = 32;
  public static final int LE = 23;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int TRUE = 36;
  public static final int error = 1;
  public static final int EQ = 25;
  public static final int TIMES = 19;
  public static final int ELSE = 5;
  public static final int WHILE = 7;
  public static final int FLOAT = 34;
  public static final int THEN = 13;
  public static final int NE = 26;
  public static final int END = 11;
  public static final int STRING = 35;
  public static final int FALSE = 37;
  public static final int GT = 22;
  public static final int PRINT = 3;
  public static final int DO = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DEFINE",
  "PRINT",
  "IF",
  "ELSE",
  "ELSEIF",
  "WHILE",
  "LOOP",
  "FUNCTION",
  "RETURN",
  "END",
  "DO",
  "THEN",
  "AND",
  "OR",
  "NOT",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "LT",
  "GT",
  "LE",
  "GE",
  "EQ",
  "NE",
  "ASSIGN",
  "LPAREN",
  "RPAREN",
  "SEMICOLON",
  "COMMA",
  "ID",
  "INT",
  "FLOAT",
  "STRING",
  "TRUE",
  "FALSE",
  "UMINUS"
  };
}

